#pragma once

#define VIAL_KEYBOARD_UID {0x13, 0x22, 0xA6, 0xF2, 0x5B, 0x8C, 0x75, 0xAE}

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING

#define WS2812_DI_PIN D6
#define RGBLIGHT_TIMEOUT 120000
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_BREATHING
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_TWINKLE
