#pragma once

#define VIAL_KEYBOARD_UID {0x13, 0x22, 0xA6, 0xF2, 0x5B, 0x8C, 0x75, 0xAE}

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING
#define LAYER_STATE_8BIT

#define WS2812_DI_PIN D6
#undef RGBLIGHT_LED_COUNT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_TWINKLE
#undef RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_LED_COUNT 62
